config/routes.rb
Rails.application.routes.draw do

  get "/", to: "welcome#index", as: :root

  get "/games", to: "games#index", as: :games
  get "/games/new", to: "games#new", as: :new_game
  post "/games/new", to: "games#create", as: false
  get "/games/show/:name", to: "games#show", as: :show_game
  get "/games/ranking", to: "games#ranking", as: :ranking

  get "/users/new", to: "users#new", as: :new_user
  post "/users/new", to: "users#create", as: false
  get "/user/games/:name", to: "users#games", as: :show_user

  get "/login/new", to: "login#new", as: :new_login
  post "/login/new", to: "login#create", as: false
  get "/login/destroy", to: "login#destroy", as: :destroy_login

  post "/games/show/:name", to: "review#create", as: false

  get "/games/quests/:id", to: "quests#index", as: :quests
  get "/games/quests/new/:id", to: "quests#new", as: :new_quest
  post "/games/quests/new/:id", to: "quests#create", as: false

end

app/models/game.rb
class Game < ActiveRecord::Base

  validates_uniqueness_of :name, :history
  validates_presence_of :name, :history, :gender, :game_picture

  has_many :reviews, class_name: Review, foreign_key: :id_game
  has_many :quests, class_name: Quest, foreign_key: :id_game

  has_attached_file :game_picture, :styles => { :medium => "300x300>", :thumb => "100x100>", :background => "1200x900>" }, :default_url => "logo.png"
  validates_attachment_content_type :game_picture, :content_type => /\Aimage\/.*\Z/

  def score
    reviews.inject(0) {|sum, review| sum + review[:note]}
  end 

  def info
    # "criado por: #{developer}"
    "#{developer} - #{gender} - #{score} pontos"
    
  end

end

app/models/my_games.rb
class MyGames < ActiveRecord::Base
end

app/models/quest.rb
class Quest < ActiveRecord::Base
end

app/models/review.rb
class Review < ActiveRecord::Base

  validates_uniqueness_of :id_user, scope: :id_game

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "logo.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_uniqueness_of :email

  has_many :games, class_name: Review, foreign_key: :id_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
    @search_game = Game.where("name LIKE '%#{params[:search]}%'") if params[:search]
  end

  def ranking 
    @games = Game.all.limit(20).sort{ |x,y| y.score <=> x.score }
  end

  def new
    @new_game = Game.new
  end

  def create
    @new_game = Game.create(games_params)

    if @new_game.save 
      redirect_to games_path
      $score_games ||= Hash.new
      $score_games["#{@new_game.name}"] = 0
    else
      render :new
    end
  end

  def show
    @game = Game.find_by_name(params[:name])
    @review = Review.new
    @reviews = @game.reviews
    $score_games ||= Hash.new

    $value = 0
  end

  private
  def games_params
    params.require(:game).permit(
      :name, 
      :developer,
      :year,
      :history,
      :gender,
      :accept,
      :avaliable,
      :game_picture,
      :classication,
      :description,
      :multiplayer,
      :coop,
      :campaign,
      :legend,
      :dubbing,
      :requirements
    )
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      session[:user_id] = user.id
      flash[:notice] = "Bem-vindo #{current_user.name}"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Obrigado pela presença."

    redirect_to root_path
  end

end

app/controllers/quests_controller.rb
class QuestsController <  ApplicationController

  def index
    @game = Game.find params[:id]
    @quests = @game.quests
  end

  def new
    @new_quest = Quest.new
  end

  def create
    @game = Game.find params[:id]
    @new_quest = Quest.create(quest_params)
    @new_quest.id_game = @game.id

    if @new_quest.save
      flash[:notice] = "Quest criada com sucesso!"
      redirect_to quests_path(@game.id)
    else
      flash[:notice] = "Ops, ouve algum erro, verifique se a missão ja existe."
      redirect_to quests_path(@game.id)
    end

  end

  private
  def quest_params
    params.require(:quest).permit(
      :name,
      :id_game,
      :objective,
      :requirements,
      :reward
    )
  end

end

app/controllers/review_controller.rb
class ReviewController < ApplicationController

  def create
    @game = Game.find_by_name params[:name]
    @review = Review.create(games_params)
    @review.id_user = current_user.id
    @review.id_game = @game.id

    if @review.save
      redirect_to show_game_path(@game.name)
    else
      redirect_to show_game_path(@game.name)
    end

  end

  private
  def games_params
    params.require(:review).permit(
      :id_user,
      :id_game,
      :review,
      :note
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

  end

  def new
    @new_user = User.new
  end

  def create
    @new_user = User.create(user_params)
    @new_user.adm = false

    if @new_user.save
      redirect_to games_path
    else
      render :new
    end

  end

  def games
    @user = User.find_by_name(params[:name])
    @games = current_user.games
  end

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :adm
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController  < ApplicationController

  def index
    @games = Game.all.to_a
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def session_nav
    if current_user
      render "layouts/loged"
    else
      render "layouts/login"
    end
  end

  def show_new_review
    if current_user
      render "review"
    end
  end

  def card_rank(rank)
    case rank
      when 0
        "gold"
      when 1
        "silver"
      when 2
        "bronze"
      end
  end

end

app/views/games/_review.html.erb
<%= form_for @review, url: show_game_path(@game.name) do |review| %>
  <%= review.label :note, "Nota" %> <small>de 1 a 5</small>
  <%= review.number_field :note, in: 1..5, value: "1", style: "text-align: center;" %><br>

  <%= review.label :review, "Deixe sua opinião" %><br>
  <%= review.text_area :review, class: "text_area" %>

  <%= review.submit "Enviar review", class: "btn btn-primary" %>
<% end %>

app/views/games/index.html.erb
<div class="panel panel-default well" style="margin-top: 70px; padding: 2px; border-left: none; border-right: none; border-radius: 0px;">
  <div class="panel-body">

    <h3 style="float:left; top: -15px; position:relative;"><span class="label label-primary">New</span> Você pode adicionar um jogo que ainda não temos !</h3>

    <%= link_to new_game_path do  %>
      <button type="button" class="btn btn-primary" style="float:right;">Add Game</button>
    <% end %>

  </div>
</div>    
 
<% if @search_game %>
  <% @search_game.each do |p| %>
    <p> 
      <% p.name %>

      <% @games.each do |game| %>
        <% if  game.name == p.name %>

          <div class="col-xs-12 col-sm-6 col-md-3" style="margin: -1px;" >
            <div class="thumbnail well" style="height: 400px; text-align: center;  border-color: green; background: lightgreen;">
              <%= image_tag game.game_picture.url, style: "width: 240px; height: 200px;", 
              class: "img-border" %>
              <div class="caption">
                <h3><%= game.name %></h3>
                <p><%= game.developer %> - <%= game.gender %></p>
                <p><%= link_to "Saiba mais...", show_game_path(game.name), class: "btn btn-primary" %></p>
              </div>
            </div>
          </div>

        <% end %>
      <% end %>     
    </p>
  <% end %>
<% end %>

<div class="container">
<div class="row" style="text-align: center;">

<% @games.reverse.each do |game| %>

  <div class="col-xs-12 col-sm-6 col-md-3" style="margin: -1px;" >
    <div class="thumbnail well" style="height: 400px; border-color: black;">
      <%= image_tag game.game_picture.url, style: "width: 240px; height: 200px;", class: "img-border" %>
      <div class="caption">
        <h3><%= game.name %></h3>
        <p><%= game.developer %> - <%= game.gender %></p>
        <p><%= link_to "Saiba mais...", show_game_path(game.name), class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

<% end %>

</div>

</div>

app/views/games/new.html.erb
<%= stylesheet_link_tag 'form', media: 'all', 'data-turbolinks-track' => true %>

<div class="container" style="margin-top: 60px; ">
<h1>Novo Jogo</h1> <small>Os campos com * são obrigatórios</small>

<div class="panel panel-default well">
  <div class="panel-body">

    <%= form_for @new_game, url: new_game_path do |game| %>
      <label for="inputPassword3" class="col-sm-2 control-label">* Imagen do jogo</label>
      <small>selecione uma imagen pra aprensentar o jogo</small>
      <%= game.file_field :game_picture, class: "form-control" %><br>

      <label for="inputPassword3" class="col-sm-2 control-label">* Nome do jogo</label>
      <small>não utilize abreviações</small>
      <p><%= game.text_field :name, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Desenvolvedora</label>
      <small>Empresa ou pessoa que desenvolveu o game</small>
      <p><%= game.text_field :developer, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Ano de lançamento</label>
      <p><%= game.text_field :year, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">* História do jogo</label>
      <small>conte a história do jogo com meros detalhes</small>
      <p><%= game.text_area :history, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">* Gênero</label>
      <small>ex: FPS, RPG, Aventura</small>
      <p><%= game.text_field :gender, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Disponibilidade</label>
      <small>ex: PS3, PC, Xbox 360</small>
      <p><%= game.text_field :avaliable, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Classificação indicativa</label>
      <small>ex: 18</small>
      <p><%= game.text_field :classication, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Descrisão</label>
      <small>Sem spoilers, apenas descrisão.</small>
      <p><%= game.text_field :description, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Multiplayer?</label>
      <p><%= game.check_box :multiplayer, class: "form-control" %></p>
    
      <label for="inputPassword3" class="col-sm-2 control-label">Co-op?</label>
      <p><%= game.check_box :coop, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Campanha?</label>
      <p><%= game.check_box :campaign, class: "form-control" %></p>
    
      <label for="inputPassword3" class="col-sm-2 control-label">Legendado nos idiomas:</label>
      <small>ex: português, italiano</small>
      <p><%= game.text_field :legend, class: "form-control" %></p>
    
      <label for="inputPassword3" class="col-sm-2 control-label">Dublado nos idiomas:</label>
      <small>ex: português, italiano</small>
      <p><%= game.text_field :dubbing, class: "form-control" %></p>
      
      <label for="inputPassword3" class="col-sm-2 control-label">Requirimentos minimos:</label>
      <small>Seguindo pela ordem: Sistema operacional, processador, placa de video</small>
      <p><%= game.text_field :requirements, class: "form-control" %></p>

      <p><%= game.submit "Cadastrar game", class: "btn btn-default" %></p>
    <% end %>

  </div>
</div>
</div>

app/views/games/ranking.html.erb
<span style="font-size: 400%; float: right; margin-right: 20px;">Top 20</span>
<h1 class="well" style="width: 100%; border-radius: 0px; margin-top: 70px;">
  Ranking de jogos
</h1>

<div class="container">


  <div class="row" style="text-align: center; margin-top: 50px;">

    <% @games.each_with_index do |game,index| %>
      
      <div class="col-xs-12 col-sm-6 col-md-3" style="margin: -1px;" >
        <div class="thumbnail well game-card <%= card_rank(index) %>">
          <%= image_tag game.game_picture.url, style: "width: 240px; height: 200px;" %>
          <div class="caption">
            <h3><%= game.name %></h3>
            <p><%= game.info %></p>
            <p><%= link_to "Saiba mais...", show_game_path(game.name), class: "btn btn-primary" %></p>
          </div>
        </div>
      </div>

    <% end %>

  </div>

</div>

app/views/games/show.html.erb
<%= stylesheet_link_tag 'form', media: 'all', 'data-turbolinks-track' => true %>

<div class="container bg-show-game" style="margin-top: 70px;">

<h1 class="well">
  <%= @game.name %> <span class="label label-primary"><%= @game.gender %></span>
  <small style="float: right;"><%= link_to "Quests", quests_path(@game.id) %></small>
</h1>

<p style="postion: relative; text-align: center; margin-right: 20px;" >

<div class="row" style="text-align:center; margin: 30px;">

  <div class=" col-xs-12 col-ms-6 col-md-6">
    <%= image_tag @game.game_picture.url(:medium), style: "border: 1px solid black;" %></p>
  </div>

  <div class=" col-xs-12 col-ms-6 col-md-6">
    <p>
      <%= @game.history %>
    </p>
  </div>
</div>

<div class="row" style="margin: 0px;">
  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Desenvolvedora:</b>
    <%= @game.developer %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Ano de lançamento: </b>
    <%= @game.year %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Disponivel para: </b>
    <%= @game.avaliable %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Classificação indicativa:  </b>
    <%= @game.classication %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Multiplayer:  </b>
    <%= @game.multiplayer %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Co-op:  </b>
    <%= @game.coop %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Campanha:  </b>
    <%= @game.campaign %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Legendado em:  </b>
    <%= @game.legend %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Dublado em:  </b>
    <%= @game.dubbing %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Requirimentos:  </b>
    <%= @game.requirements %>
  </p>

  <p class="col-xs-12 well col-ms-6 col-md-4"><b>Pontuação: </b>

    <% @reviews.each do |review| %>
      <% $value = review.note + $value %>
    <% end %>
    <%= $value %>
    <% $score_games["#{@game.name}"] = $value %>
  </p>
</div>

<div class="panel well" style="padding: 30px; text-align: center;">
  <h3>Avaliações</h3>
  <%= show_new_review %>


  <% @reviews.last(10).each do |review| %>
      <div class="review">
        <b><%= User.find_by_id(review.id_user).name %>
        <small>Nota: <%= review.note %></small></b><br>
        <%= review.review %>
      </div>
  <% end %> 
  
</div>

</div>

app/views/layouts/_loged.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to "Meus Jogos", show_user_path(current_user.name) %></li>
    <li class="divider"></li>
    <li><%= link_to "Sair", destroy_login_path %></li>
  </ul>
</li>

app/views/layouts/_login.html.erb
<li><%= link_to "Cadastre-se", new_user_path %></li>
<li><%= link_to "Login", new_login_path %></li>

app/views/layouts/_search.html.erb
<div class="form-group">
  <%= form_tag games_path, method: :get do %>
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar jogo" %>
    <%= submit_tag "Buscar", class: "btn btn-default" %>
  <%  end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoraoDeJogos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "logo.png", style:"width: 30px;", class: "invert-color" %>
      <% end %>
      <%= link_to "Porão de Jogos", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Lista de jogos", games_path %></li>
        <li><%= link_to "Ranking", ranking_path %></li>
        <li><%= link_to flash[:notice], "", style: "color: lightgreen;" %></li>
      </ul>
      <form class="navbar-form navbar-right" role="search">
        <%= render "layouts/search" if request.url.to_s == "http://localhost:3000/games" %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <%= session_nav %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<nav>
  <ul>
    
    
  </ul>
</nav>

<%= yield %>

</body>
</html>

app/views/login/new.html.erb
<div class="container" style="margin-top: 50px;">
  <h1>Login</h1>


  <div class="panel panel-default well">
  <div class="panel-body">

    <%= form_for :login, url: new_login_path do |user| %>
      <label for="inputPassword3" class="col-sm-2 control-label">E-mail</label>
      <p><%= user.text_field :email, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Senha</label>
      <p><%= user.password_field :password, class: "form-control" %></p>
      
      <p><%= user.submit "Logar", class: "btn btn-default" %></p>
    <% end %>

  </div>
</div>


</div>

app/views/quests/index.html.erb
<div class="panel panel-default well" style="margin-top: 70px; padding: 2px; border-left: none; border-right: none; border-radius: 0px;">
  <div class="panel-body">

    <h3 style="float:left; top: -15px; position:relative;"><span class="label label-info">Info</span> Para cada conquista, uma missão. <small>Adicione uma quest para este game.</small></h3>

    <%= link_to new_quest_path(@game.id) do  %>
      <button type="button" class="btn btn-primary" style="float:right;">Add nova quest</button>
    <% end %>

  </div>
</div>

<div class="container" style="margin-top: 50px;">
  <table>
    <ul>
      <% @quests.reverse.each do |quest| %>
      <li><h3><b><%= quest.name %></b></h3></li>
      <p><%= quest.objective %></p>
      <b>Recompensa:</b> <small><%= quest.reward %></small>
      <br><br>
      <% end %>
    </ul>
  </table>
</div>

app/views/quests/new.html.erb
<div class="container" style="margin-top: 50px;">
  <h1>Nova quest</h1>


  <div class="panel panel-default well">
  <div class="panel-body">

    <%= form_for @new_quest, url: new_quest_path do |quest| %>
      <label for="inputPassword3" class="col-sm-2 control-label">Nome da missão</label>
      <p><%= quest.text_field :name, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Requisitos</label>
      <p><%= quest.text_field :requirements, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Objetivo</label>
      <p><%= quest.text_field :objective, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Recompensa</label>
      <p><%= quest.text_field :reward, class: "form-control" %></p>
      
      <p><%= quest.submit "Adicionar quest", class: "btn btn-default" %></p>
    <% end %>

  </div>
</div>

app/views/users/games.html.erb
<div class="panel panel-default well" style="margin-top: 70px; padding: 2px; border-left: none; border-right: none; border-radius: 0px;">
  <div class="panel-body">

    <h3 style="float:left; top: -15px; position:relative;"><span class="label label-primary">New</span> Você pode adicionar um jogo que ainda não temos !</h3>

    <%= link_to new_game_path do  %>
      <button type="button" class="btn btn-primary" style="float:right;">Add Game</button>
    <% end %>

  </div>
</div>    

<div class="container">
<p>Seus jogos são aqueles do qual você mandou um review.</p>

<div class="row" style="text-align: center;">

<% @games.reverse.each do |game| %>
<% game = Game.find_by_id(game.id_game  ) %>

  <div class="col-xs-12 col-sm-6 col-md-3" style="margin: -1px;" >
    <div class="thumbnail well" style="height: 400px; border-color: black;">
      <%= image_tag game.game_picture.url, style: "width: 240px; height: 200px;" %></p>
      <div class="caption">
        <h3><%= game.name %></h3>
        <p><%= game.developer %> - <%= game.gender %></p>
        <p><%= link_to "Saiba mais...", show_game_path(game.name), class: "btn btn-primary" %></p>
      </div>
    </div>
  </div>

<% end %>

</div>

</div>

app/views/users/new.html.erb
<div class="container" style="margin-top: 50px;">
  <h1>Novo usuario</h1>


  <div class="panel panel-default well">
  <div class="panel-body">

    <%= form_for @new_user, url: new_user_path do |user| %>

      <label for="inputPassword3" class="col-sm-2 control-label">Nome</label>
      <p><%= user.text_field :name, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">E-mail</label>
      <p><%= user.text_field :email, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Senha</label>
      <p><%= user.password_field :password, class: "form-control" %></p>

      <label for="inputPassword3" class="col-sm-2 control-label">Confirmar senha</label>
      <p><%= user.password_field :password_confirmation, class: "form-control" %></p>
      
      <p><%= user.submit "Cadastrar ususario", class: "btn btn-default" %></p>
    <% end %>

  </div>
</div>


</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track' => true %>

<div class="jumbotron" style="height: 100vh;">
  <h1>Porão de Jogos</h1>
  <p>A casa de todo conhecimento gamer.</p>
</div>

<div class="container" >

  <h2>Tudo sobre seu jogos preferidos <span class="label label-info">New</span></h2>
  <h5>Recen adicionados</h5>

  <div class="row">
    <% @show_games = 0 %>
    <% @games.reverse.each do |game| %>
      <% if @show_games <= 6 %>

        <div class=" col-xs-12 col-sm-6 col-md-6"> 
          <div class="well"> 
          <a class="media-left" href="#" style="margin: 40px;">
            <%= image_tag game.game_picture.url(:medium), style: "width: 64px; height: 64px;", class: "img-border" %></p>
          </a>
          <div class="media-body">
            <h4 class="media-heading"><%= game.name %> <small><%= game.gender %></small></h4>
            <small><%= game.description.first(150) %></small>
          </div>
          </div>
        </div>

      <% end %>

    <% end %>

  </div>


</div>